// samples/svelte-kit/src/routes/posts/[...slug]/+page.svelte
<script lang="ts">
  import type { PageProps } from "./$types";
  import Markdown from "svelte-exmarkdown";
  import { markdownPlugins } from "$lib/mdSveltePlugins";

  let { data }: PageProps = $props();

  const post = $derived(data.post);
  const plugins = markdownPlugins;
</script>

<article class="post">
  <header>
    <h2>{post.title}</h2>
  </header>
  <div class="content">
    <Markdown md={post.content} {plugins} />
  </div>
  <footer>
    <p>By {post.author}</p>
    <time>{post.date}</time>
  </footer>
</article>

// samples/next-mdx-static-import/app/posts/[slug]/page.tsx
import { allPosts } from "content-collections";
import { notFound } from "next/navigation";

type Props = {
  params: {
    slug: string;
  };
};

export default async function Post({ params: { slug } }: Props) {
  const post = allPosts.find((post) => post.slug === slug);
  if (!post) {
    return notFound();
  }

  const MdxContent = post.mdxContent;

  return (
    <article className="post">
      <header>
        <h2>{post.title}</h2>
      </header>
      <div className="content">
        <MdxContent />
      </div>
      <footer>
        <p>By {post.author}</p>
        <time>{post.date}</time>
      </footer>
    </article>
  );
}
