// samples/next-pages/src/pages/posts/[slug].tsx
import { allPosts } from "content-collections";
import { MDXContent } from "@content-collections/mdx/react";
import { GetServerSidePropsContext, InferGetStaticPropsType } from "next";
import Metadata from "@/src/components/Metadata";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export default function Post({ title, summary, code, author, date }: Props) {
  return (
    <article className="post">
      <Metadata title={title} description={summary} />
      <header>
        <h2>{title}</h2>
      </header>
      <div className="content">
        <MDXContent code={code} />
      </div>
      <footer>
        <p>By {author}</p>
        <time>{date}</time>
      </footer>
    </article>
  );
}

type Params = {
  slug: string;
};

export function getStaticPaths() {
  return {
    paths: allPosts.map((post) => ({ params: { slug: post._meta.path } })),
    fallback: false,
  };
}

export function getStaticProps({ params }: GetServerSidePropsContext<Params>) {
  const post = allPosts.find((post) => post._meta.path === params?.slug);
  if (!post) {
    return { notFound: true };
  }

  return {
    props: {
      title: post.title,
      summary: post.summary,
      code: post.code,
      author: post.author,
      date: post.date,
    },
  };
}

// samples/solid/src/routes/posts/[slug].tsx
import {
  cache,
  createAsync,
  RouteDefinition,
  RouteSectionProps,
} from "@solidjs/router";
import { allPosts } from "content-collections";
import { Show } from "solid-js";

const getPost = cache(async (slug: string) => {
  "use server";

  const post = allPosts.find((post) => post._meta.path === slug);
  if (post) {
    return {
      title: post.title,
      html: post.html,
      date: post.date,
      author: post.author,
    };
  }
}, "posts");

export const route = {
  load: ({ params }) => getPost(params.slug),
} satisfies RouteDefinition;

export default function Post(props: RouteSectionProps) {
  const post = createAsync(() => getPost(props.params.slug));

  return (
    <Show when={post()}>
      <Show when={post()} fallback={<h2>Post not found.</h2>}>
        <article class="post">
          <header>
            <h2>{post()?.title}</h2>
          </header>
          <div class="content" innerHTML={post()?.html}></div>
          <footer>
            <p>By {post()?.author}</p>
            <time>{post()?.date}</time>
          </footer>
        </article>
      </Show>
    </Show>
  );
}
